---
title: "My list of publications"
output:
  distill::distill_article:
    toc: false
    toc_depth: 2
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# 2020
### Breeding stage, not sex, affects foraging characteristics in masked boobies at Rapa Nui
**Authors**: **Lerma M**, Dehnhard N, Luna-Jorquera G, Voigt CC, Garthe S  
**Abstract** Sexual segregation in foraging occurs in some species and populations of boobies (Sulidae), but it is not a general pattern. Sexual segregation in foraging may occur to avoid competition for food, and this competition may intensify during specific stages of breeding. We examined sexual segregation in foraging in relation to breeding stage in masked boobies _Sula dactylatra_ at Rapa Nui by tracking simultaneously incubating and chick-rearing birds using GPS recorders (n = 18) and collected a total of 11 regurgitate samples. Stable isotope analyses (δ13C and δ15N) of whole blood samples were carried out in 20 birds. There were no differences in foraging trip parameters or diet between females and males. Both sexes traveled farther and for longer while incubating than while rearing chicks. Isotopic niches (δ13C and δ15N) overlapped to some degree among all groups at all times, but the lowest overlap between sexes occurred during incubation. While preying on ephemerally distributed flying fish, vertical or horizontal competition avoidance may be almost impossible, and thus females and males share their foraging grounds. Since birds were tracked simultaneously, shorter foraging trips of chick-rearing birds must be an effect of the constraints of provisioning the chick. Differences observed in δ15N and δ13C values between sexes may be caused by subtle differences in their foraging behaviors, or by differences in physiology linked to breeding. Our findings suggest that local oceanography and its inherent food distribution are determinants for sexual segregation in foraging patterns in masked boobies and possibly also other booby species.  
**Read more:** [Full publication](https://link.springer.com/article/10.1007/s00265-020-02921-1)

### Foraging ranges of Humboldt penguins _Spheniscus humboldti_ from Tilgo island: the critical need for protecting a unique marine habitat
**Authors**: Quispe R, **Lerma M**, Luna N, Portflitt-Toro M, Serratosa J, Luna-Jorquera  
**Abstract** The largest population of Humboldt Penguins resides in a fertile archipelago of the north-central coast of Chile, formed by eight islands in proximity to upwelling centers of the Humboldt Current System. However, five of these islands lack legal protection. Here, we report the results of breeding Humboldt Penguins tracked while foraging from Tilgo Island. The average and maximum foraging radii around the colony were 22 km and 43 km, respectively. Our data indicate that trip ranges overlap areas proposed for industrial projects. Because Humboldt Penguins are sentinels of local ecosystem health, this underscores the value of expanding conservation zones in this unique marine location.  
**Read more:** [Full publication](https://www.marineornithology.org/PDF/48_2/48_2_205-208.pdf)

### Foraging ecology of a marine top predator in the Eastern Tropical Pacific over 3 years with different ENSO phases
**Authors**: **Lerma M**, Castillo-Guerrero JA Hernandez-Vazquez S, Garthe S  
**Abstract** The El Niño Southern Oscillation (ENSO) is a recurrent climatic pattern with important ecological consequences for seabirds due to its impacts on the abundance and distribution of food resources. We investigated the effects of ENSO phases on the foraging ecology of a marine top predator at Clarion Island in the Eastern Tropical Pacific using GPS and time-depth recorder data and regurgitates from incubating masked boobies (_Sula dactylatra_) during 3 consecutive years. Foraging locations were recorded in 2016 (El Niño, one female, three males), 2017 (neutral; six females, nine males), and 2018 (La Niña; eight females, ten males). Local sea surface temperature (SST) and chlorophyll-a concentration (CHL) within the birds’ foraging range were compared among the 3 years. Regurgitates were collected opportunistically from 25 and 31 incubating adults in 2017 and 2018, respectively. Average local CHL and SST were similar among years (mean SST 25 °C; mean CHL 0.10 and of 0.09 mg m−3 in January and March, respectively). Masked boobies travelled a maximum of 66 ± 34 km from the colony. The maximum trip duration was 7.7 ± 3.4 h and total distance travelled during a foraging trip was 164 ± 73 km, with no sex- or year-related differences. Masked boobies mainly caught flying fish, but their diet also included one squid and six other fish families. In contrast to previously reported changes in foraging ecology of seabirds, masked boobies at Clarion Island seemed to be unaffected during El Niño, because the local oceanography was relatively unperturbed by ENSO oscillations.  
**Read more:** [Full publication](https://doi.org/10.1007/s00227-020-03699-6)

### Foraging ecology of masked boobies (_Sula dactylatra_) in the world’s largest ‘oceanic desert’
**Authors**: Lerma M, Serratosa J, Luna-Jorquera G, Garthe S  
**Abstract** The South Pacific Gyre has the most hyper-oligotrophic waters in the world and is considered the largest “oceanic desert.” Rapa Nui (Easter Island), located within the South Pacific Gyre, is a breeding ground for masked boobies (_Sula dactylatra_), which are seabirds with a foraging range that effectively confines them within the gyre. The foraging ecology of this species in the gyre was examined by attaching GPS and time-depth devices to chick-rearing adult birds (9 and 14 birds in 2016 and 2017, respectively) and by collecting regurgitates (18 and 15 samples in 2016 and 2017, respectively). In addition, the birds’ foraging ecology between years was compared. Masked boobies traveled in various directions, dived at unspecific locations, and explored areas < 110 km from the colony. Local environmental conditions were not significantly different between years, and differences in foraging parameters (maximum foraging range, trip duration, and dive depth) were greater among individuals than between years. The foraging characteristics of masked boobies suggest that resources were ephemerally distributed around the colony, with similar abundances across years. Under these conditions, traveling to unspecific locations may increase the area covered and the probability of prey encounter. The spatial and temporal consistencies in environmental conditions explain the uniformity of foraging parameters between years. The ability of masked boobies to exploit ephemerally distributed resources in seascapes like Rapa Nui may help explain its pantropical distribution.  
**Read more:** [Full publication](https://link.springer.com/article/10.1007/s00227-020-03700-2)

### Zinc concentrations in Blue-footed booby (_Sula nebouxii_) eggs, nestlings, and adults
**Authors**: **Lerma M**, Castillo-Guerrero JA, Garcia-Hernandez J, Fernandez G   
**Abstract** Zinc is essential for animal metabolism, but the variation in Zn concentrations within seabird populations has been seldom explored. We collected Blue-footed booby (_Sula nebouxii_) eggs during 2012 and 2013 and blood samples from nestlings and adults during 2011 and 2012 in Sinaloa, Mexico, to evaluate differences in Zn concentrations among years, ages, sexes, and breeding stages. Zinc concentrations in eggs ranged between 27.3 and 64.9 ppm (dry weight), whereas Zn levels in the blood of nestlings and adults ranged between 16.1 and 53.1 ppm (dry weight). Egg Zn concentrations did not differ due to developmental stage, although Zn concentrations were significantly higher in 2013 than in 2012. Nestling Zn concentrations differed between years and decreased gradually with age. Chicks had significantly higher Zn concentrations than those of adults. Once nestlings stopped growing, females presented higher Zn concentrations than males. Adult Zn concentrations were higher during the pre-laying period than during the other breeding stages. Our results suggest that growth, sex, and breeding stage affect blood Zn concentrations, which may be due to stage-specific requirements. When compared with those of other seabird species, the Zn concentrations reported here are intermediate, and we did not detect adverse effects on either nestlings or adults.  
**Read more:** [Full publication](https://doi.org/10.1016/j.seares.2020.101952)

# 2017
### Non-Breeding Distribution, Abundance, and Roosting Habitat Use of the American Oystercatcher (Haematopus palliatus frazari) in Sinaloa, Mexico
**Authors**: **Lerma M**, Castillo-Guerrero JA, Palacios E   
**Abstract** The American Oystercatcher (_Haematopus palliatus frazari_) is federally listed as endangered in Mexico due to habitat loss and small population size. Recent surveys indicate that the State of Sinaloa supports about half of the breeding population in Mexico. However, no information is available about the non-breeding ecology in Mexico. To assess American Oystercatcher distribution, abundance, and roosting habitat use during the nonbreeding season (3 August 2014-23 January 2015), six bays were surveyed in Sinaloa. A total of 1,351 American Oystercatchers were detected using this area based on maximum count per roosting site at or near high tide. American Oystercatchers roosted in flocks of variable size (3–253 individuals per flock) with Bahía Santa María hosting the main roosting sites in Sinaloa. Mangrove islands and mudflats had larger numbers of individuals than expected relative to the availability of those habitats. The non-breeding Sinaloa population comprised approximately 45.0% of the total H. p. frazari population estimate (n = 3,000 individuals). Bahía Santa María represented 74.6% of the non-breeding population observed in Sinaloa. Thus, Sinaloa, and particularly Bahía Santa María, stand out as critical sites for the conservation of this subspecies. Hypothesized threats to American Oystercatchers were predators, livestock, and human activities.  
**Read more:** [Full Publication](https://doi.org/10.1675/063.040.sp111)

### Lead, cadmium and mercury in the blood of the blue-footed booby (Sula nebouxii) from the coast of Sinaloa, Gulf of California, Mexico  
**Authors**: **Lerma M**, Castillo-Guerrero JA, Ruelas-Inzunza J, Fernandez, G  
**Abstract** We used blood samples of the Blue-footed Booby, considering sex (female and male) and age-class (adult and chick) of individuals at different breeding stages during two breeding seasons (2010–2011 and 2011–2012) in Isla El Rancho, Sinaloa, to determine lead, cadmium, and mercury concentrations. Lead and cadmium concentrations were below our detection limit (0.05 and 0.36 ppm, respectively). A higher concentration of mercury was found in early stages of breeding, likely related to changes in mercury environmental availability. Mercury concentrations in adults did not relate with their breeding output. Males and adults had higher mercury concentration than females and chicks. We provide information of temporal, sex and age-related variations in the concentrations of mercury in blood of the Blue-footed Booby.  
**Read more:** [Full Publication](https://doi.org/10.1016/j.marpolbul.2016.06.049)

# 2016
### Environmentally-mediated flexible foraging strategies in Brown Boobies in the Gulf of California.
**Authors**: Castillo-Guerrero JA, **Lerma M**, Mellink E, Suazo-Guillén E, Peñaloza-Padilla EA  
**Abstract** The Brown Booby _Sula leucogaster_ is a seabird with a pantropical distribution across a wide variety of oceanic environments. Sexual size dimorphism in Brown Boobies has been proposed as an explanation for intersexual differences in foraging, but results have been inconsistent. We investigated whether there is context-dependent foraging behaviour driven by local environmental conditions. In this study, we evaluated (1) inter-sex differences in foraging behaviour (by capillary tubes, temperature and depth recorders, and diet) at two colonies in the Gulf of California: Isla San Jorge (ISJ) and Farallón de San Ignacio (FSI) and, (2) intercolonial and interannual differences in foraging behaviour, and (at ISJ) their relationship with local-scale environmental variation, using 5-day composite images of sea surface temperature (SST) and primary productivity (PP) as proxies. Inter-sex differences were few and inconsistent between years, and smaller than overall differences between years and localities. At ISJ, Brown Boobies included more prey species in their diet (27 vs. 19 spp.) and dove shallower (2.3 vs. 3.14 m) than at FSI. At ISJ, Brown Boobies exhibited adjustments in diving depth and prey size as a function of environmental variation: shallower plunge dives and smaller prey items were related with lower SST and higher PP values, whereas deeper dives and larger prey items were related with higher SST and lower PP values. Our results confirmed that the Brown Booby is highly plastic in its foraging ecology, which explains its ability to live in places with large-scale environmental variation (intercolony and interannual), such as tropical areas worldwide.  
**Read more:** [Full Publication](https://doi.org/10.5253/arde.v104i1.a3)