---
title: "Non-Breeding Distribution, Abundance, and Roosting Habitat Use of the American Oystercatcher (Haematopus palliatus frazari) in Sinaloa, Mexico"
authors:
  - name: Miriam Lerma
date: '2017-02-1'
output:
  distill::distill_article:
    self_contained: false
categories:
  - publications
  - shorebirds
  - tropical
---


# Abstract
The American Oystercatcher (Haematopus palliatus frazari) is federally listed as endangered in Mexico due to habitat loss and small population size. Recent surveys indicate that the State of Sinaloa supports about half of the breeding population in Mexico. However, no information is available about the non-breeding ecology in Mexico. To assess American Oystercatcher distribution, abundance, and roosting habitat use during the nonbreeding season (3 August 2014-23 January 2015), six bays were surveyed in Sinaloa. A total of 1,351 American Oystercatchers were detected using this area based on maximum count per roosting site at or near high tide. American Oystercatchers roosted in flocks of variable size (3–253 individuals per flock) with Bahía Santa María hosting the main roosting sites in Sinaloa. Mangrove islands and mudflats had larger numbers of individuals than expected relative to the availability of those habitats. The non-breeding Sinaloa population comprised approximately 45.0% of the total H. p. frazari population estimate (n = 3,000 individuals). Bahía Santa María represented 74.6% of the non-breeding population observed in Sinaloa. Thus, Sinaloa, and particularly Bahía Santa María, stand out as critical sites for the conservation of this subspecies. Hypothesized threats to American Oystercatchers were predators, livestock, and human activities.

[Full Publication](doi: https://doi.org/10.1675/063.040.sp111)
