---
title: "resting_locations"
description: |
  A short description of the post.
author:
  - name: Miriam Lerma
    url: {}
date: 2024-10-08
output:
  distill::distill_article:
    self_contained: false
---

# Intro

In this post we will try to identify resting locations based on the low movements and high number of locations on a specific point.

## Data

```{r}
DataFolder<-paste0(here('_posts/2024-13-15-package-larus'))
```

```{r}
DataFolder
```

```{r}
library(tidyverse)
```

## Load data

```{r}
Gull_original<-read_csv(paste0(DataFolder,'/Gull_data.csv'))
```


## Heat map


## Function 03. calculate_speed

```{r}
calculate_speed<-function(GPS_data=GPS_data,
                          column_latitude=column_latitude,
                          column_longitude=column_longitude,
                          column_datetime=column_datetime){

  GPS_data<-GPS_data
  GPS_data$Longitude <- GPS_data[[column_longitude]]
  GPS_data$Latitude <- GPS_data[[column_latitude]]
  GPS_data$dt <- GPS_data[[column_datetime]]
    
  GPS_coords<- GPS_data[,c('Longitude','Latitude')]
  GPS_spatial <- sp::SpatialPointsDataFrame(coords = GPS_coords, data = GPS_data)
  sp::proj4string(GPS_spatial)= sp::CRS("+init=epsg:4326")
  GPS_distance<-sapply(2:nrow(GPS_spatial),
                             function(i){geosphere::distm(GPS_spatial[i-1,], GPS_spatial[i,])})
  GPS_distance<-c(NA,GPS_distance)
  GPS_data$distance_km<-round(GPS_distance/1000,2)
  
  times<-GPS_data[[column_datetime]]
  times_lag<-lag(times)
  time_dif<-as.numeric(difftime(times,times_lag, units="mins"))
  GPS_data$time_hr<-round(time_dif/60,2)

  GPS_data$speed_kmh<-round(as.numeric(GPS_data$distance_km/GPS_data$time_hr),2)

return(GPS_data)
}
```

Time format should already be POSTIXct

```{r}
class(Gull$UTC_datetime)
```

```{r}
Gull_speeds<-calculate_speed(GPS_data = Gull,
                column_latitude='Latitude',
                column_longitude='Longitude',
                column_datetime='UTC_datetime')
```

```{r}
Compare_speeds<-Gull_speeds[c('speed_kmh','speed_km_h')]
colnames(Compare_speeds)<-c('device_speed','calculated_speed')
```

```{r}
Compare_speeds$speed_dif<-Compare_speeds$device_speed-Compare_speeds$calculated_speed
```

```{r}
hist(Gull_speeds$speed_kmh)
```

## Function 04. identify_stopovers

When speed was low, the bird was considered in a stop over

```{r}
GPS_data<-Gull_speeds
stopover_speed<-10
```

```{r}
identify_stopovers<-function(GPS_data=GPS_data,
                         stopover_speed = stopover_speed){
  

  GPS_stopover<-GPS_data %>%
    mutate(
      stopover = case_when(
      speed_kmh > stopover_speed ~ "flight",
      TRUE  ~ "stop"
    ))
  
  #add sequence
  num_seq<-nrow(GPS_stopover)
  num_seq<-as.numeric(num_seq)
  GPS_stopover$num_seq<-paste(seq(1:num_seq))
  
  #only trips
  only_trips<-subset(GPS_stopover,GPS_stopover$stopover != "stop")
  only_trips$num_seq<-as.integer(only_trips$num_seq)
  only_trips$trip_number<-(cumsum(c(1L, diff(only_trips$num_seq)) != 1L))
  only_trips$trip_name<-str_pad(only_trips$trip_number+1, 3, pad = "0")
  only_trips$trip_names<-paste0("trip_",only_trips$trip_name)
  
  #only stopovers
  only_stopovers<-subset(GPS_stopover,GPS_stopover$stopover == "stop")
  only_stopovers$num_seq<-as.integer(only_stopovers$num_seq)
  only_stopovers$trip_number<-(cumsum(c(1L, diff(only_stopovers$num_seq)) != 1L))
  only_stopovers$trip_name<-str_pad(only_stopovers$trip_number+1, 3, pad = "0")
  only_stopovers$trip_names<-paste0("stopover_",only_stopovers$trip_name)
  
  GPS_stopover<-rbind(only_stopovers,only_trips)
  GPS_stopover<-GPS_stopover[order(GPS_stopover$num_seq),]
  
  GPS_stopover$trip_number<-NULL
  GPS_stopover$trip_name<-NULL
  
  return(GPS_stopover)
}
```

```{r}
Gull_stopover<-identify_stopovers(GPS_data=Gull_speeds,stopover_speed=10)
```



## Function 05. group_stopovers

```{r}
group_stopovers<-function (GPS_data = GPS_data, 
                           column_datetime=column_datetime,
                           column_longitude = column_longitude, column_latitude = column_latitude, 
                           column_group = column_group) 
{
    GPS_df <- as.data.frame(GPS_data)
    GPS_df <- GPS_df %>% dplyr::mutate(GPS_group = GPS_df[[column_group]])
    GPS_list <- split(GPS_df, GPS_df$GPS_group)
    Group_list <- list()
    for (i in seq_along(GPS_list)) {
      
        GPS_individual <- GPS_list[[i]]
        
        stopover <- GPS_individual %>% 
          dplyr::summarise(
            Start=dplyr::first(GPS_individual[[column_datetime]]),
            End=dplyr::last(GPS_individual[[column_datetime]]),
            Longitude = dplyr::first(GPS_individual[[column_longitude]]), 
            Latitude = dplyr::first(GPS_individual[[column_latitude]]))
        
        stopover$Group <- dplyr::first(GPS_individual[[column_group]])
        
        stopover<-stopover[,c('Group','Latitude','Longitude','Start','End')]
        
        Group_list[[i]] <- stopover
    }
    Group_df<- do.call("rbind", Group_list)
    return(Group_df)
}
```

```{r}
Gull_groupstops<-group_stopovers(GPS_data=Gull_stopover,
                                 column_datetime='UTC_datetime',
                                 column_longitude = 'Longitude',
                                 column_latitude='Latitude',
                                 column_group='trip_names')

```

```{r}
Gull_groupstops$timeduration<-round(as.numeric(difftime(Gull_groupstops$End,Gull_groupstops$Start, units="hours")),2)
```


## Group_stopovers

```{r}
group_stopovers<-
{
    GPS_df <- as.data.frame(GPS_data)
    GPS_df <- GPS_df %>% dplyr::mutate(GPS_group = GPS_df[[column_group]])
    GPS_list <- split(GPS_df, GPS_df$GPS_group)
    Group_list <- list()
    for (i in seq_along(GPS_list)) {
      
        GPS_individual <- GPS_list[[i]]
        
        stopover <- GPS_individual %>% 
          dplyr::summarise(
            Start=dplyr::first(GPS_individual[[column_datetime]]),
            End=dplyr::last(GPS_individual[[column_datetime]]),
            Longitude = dplyr::first(GPS_individual[[column_longitude]]), 
            Latitude = dplyr::first(GPS_individual[[column_latitude]]))
        
        stopover$Group <- dplyr::first(GPS_individual[[column_group]])
        
        stopover<-stopover[,c('Group','Latitude','Longitude','Start','End')]
        
        Group_list[[i]] <- stopover
    }
    Group_df<- do.call("rbind", Group_list)
    return(Group_df)
}
```


