---
title: "Raster Dist Colony"
description: |
  Create a raster using information from distance to colonies. 
author:
  - name: Miriam Lerma
    url: {}
date: 2025-04-10
preview: blog44_portada.jpg
output:
  distill::distill_article:
    self_contained: false
categories:
  - R
  - ggplot2
  - English
  - Y2025
---


# Data

```{r}
colonies_sub<-data.frame(
  name=c("Ailsa Craig","Barra Head","Bass Rock","Bempton Cliff","Bull Rock","Clare Island", "Fair Isle", "Flannan Isles","Foula","Grassholm Island","Great Saltee", "Helgoland" , "Hermaness", "Ireland’s Eye", "Lambay", "Les Etac/Alderrney","Little Skellig","Mykinesholmur","Noss" ,"Ortac","Rouzic Island","Scar Rocks","St. Kilda","Sula sgeir","Sule Skerry","Sule Stack","Troup Head","Westray"),
  
colony_lat=c(55.25,56.78,56.08,54.15,51.59,53.80,59.54,58.29,60.13,51.73,52.12,54.18,60.71,53.40,53.49,49.70,51.78,62.10,60.14,49.72,48.90,54.67,57.81,59.10,59.08,59.02,57.69,59.29),

colony_long=c(-5.12,-7.64,-2.64,-0.17,-10.27,-10.00,-1.63,-7.59,-2.07,-5.48,-6.62,7.89,-0.88,-6.06,-6.02,-2.24,-10.51,-7.68,-1.02,-2.29,-3.44,-4.70,-8.56,-6.16,-4.41,-4.51,-2.29,-2.98))

```

```{r}
head(colonies_sub)
```

## Using rasterise

```{r}
#https://stackoverflow.com/questions/77614574/how-do-i-create-a-raster-of-distance-to-nearest-feature-using-the-terra-sf-r-pac
s1 <- rbind(c(0,3),c(0,4),c(1,5),c(2,5))
s2 <- rbind(c(0.2,3), c(0.2,4), c(1,4.8), c(2,4.8))
s3 <- rbind(c(0,4.4), c(0.6,5))

library(terra)
v <- vect(list(s1,s2,s3), "lines", crs="local") |> aggregate()

r <- rast(v, res = 0.01)
r <- rasterize(v, r)
d <- distance(r)

plot(d)
```

### adapt

```{r}
library(terra)
```

```{r}
longitude <- colonies_sub$colony_lon
latitude <- colonies_sub$colony_lat
lonlat <- cbind(longitude, latitude)
```

```{r}
pts <- vect(lonlat)
```

```{r}
pts
```

```{r}
geom(pts)
```

```{r}
crdref <- "+proj=longlat +datum=WGS84"
pts <- vect(lonlat, crs=crdref)
pts
```

https://rspatial.org/spatial/3-vectordata.html


```{r}
r <- rast(pts, res = 0.01)
```

```{r}
plot(r)
```


```{r}
r <- rasterize(r)
```


```{r}
d <- distance(r)
```


```{r}
plot(d)
```


## distance

https://github.com/rspatial/terra/issues/567

```{r}
library(terra)
r <- rast(ncols=36, nrows=18, crs="+proj=longlat +datum=WGS84")
r[500] <- 1
p1 <- vect(rbind(c(0,0), c(90,30), c(-90,-30)), crs="+proj=longlat +datum=WGS84")
dp <- distance(r, p1)
plot(dp)
plot(p1,add=T)
```


### adapt 1

```{r}
colony1<-c(colonies_sub[1,3],colonies_sub[1,2])
colony1
colony2<-c(colonies_sub[2,3],colonies_sub[2,2])
colony2
colony3<-c(colonies_sub[3,3],colonies_sub[3,2])
colony3
```

```{r}
colonies<-rbind(colony1, 
                colony2, 
                colony3)
class(colonies)
head(colonies)
```

```{r}
p1 <- vect(colonies, 
           crs="+proj=longlat +datum=WGS84")
```

```{r}
library(terra)
r <- rast(ncols=36, nrows=18, crs="+proj=longlat +datum=WGS84",
          xmin = -10, xmax = 10, ymin = 50, ymax = 60)
r[500] <- 1
plot(r)
```





```{r}
p1 <- vect(colonies, 
           crs="+proj=longlat +datum=WGS84")
```

```{r}
dp <- distance(r, p1)
plot(dp)
plot(p1,add=T)
```


### adapt 2

```{r}
colony1<-c(colonies_sub[1,3],colonies_sub[1,2])
colony1
colony2<-c(colonies_sub[2,3],colonies_sub[2,2])
colony2
colony3<-c(colonies_sub[3,3],colonies_sub[3,2])
colony3
colony4<-c(colonies_sub[4,3],colonies_sub[4,2])
colony4
```


```{r}
this_colonies<-rbind(colony1, 
                colony2, 
                colony3,
                colony4
                )
class(this_colonies)
head(this_colonies)
```

```{r}
this_vector <- vect(this_colonies, 
           crs="+proj=longlat +datum=WGS84")
```

```{r}
this_raster <- rast(ncols=36, nrows=18, crs="+proj=longlat +datum=WGS84",
          xmin = -10, xmax = 10, ymin = 50, ymax = 60)
this_raster[500] <- 1
plot(r)
```



```{r}
this_calculation <- distance(this_raster, this_vector)
```


```{r}
plot(this_calculation)
plot(this_vector,add=T)
```



```{r}
class(this_calculation)
```

```{r}
library(terra)
library(ggplot2)
```

```{r}
head(this_calculation)
```

```{r}
this_layers<-as.data.frame(this_calculation, xy = TRUE)
```

```{r}
head(this_layers)
```

```{r}
ggplot(data = this_layers) +
    geom_raster(aes(x = x, y = y, fill = lyr.1)) +
    scale_fill_viridis_c() +
    theme_void() +
    theme(
      legend.position = "bottom"
    )
```


```{r}
mean(this_layers$lyr.1)/10000
```

```{r}
this_calculation$lyr.1
```

```{r}
library(here)
this_folder<-paste0(here(),"/_posts/2024-10-23-distancecolony")
this_folder
```

```{r}
class(this_calculation)
```


```{r}
writeRaster(this_calculation, filename=file.path(this_folder, "test.tif"))
```

```{r}
library(tidyverse)
```

```{r}
write_csv(colonies_sub[1:4,],paste0(this_folder,"/colonies.txt"))
```

### adapt 3

```{r}
colony1<-c(colonies_sub[1,3],colonies_sub[1,2])
colony1
colony2<-c(colonies_sub[2,3],colonies_sub[2,2])
colony2
colony3<-c(colonies_sub[3,3],colonies_sub[3,2])
colony3
colony4<-c(colonies_sub[4,3],colonies_sub[4,2])
colony4
```


```{r}
this_colonies<-rbind(colony1, 
                colony2, 
                colony3,
                colony4
                )
class(this_colonies)
head(this_colonies)
```

```{r}
this_vector <- vect(this_colonies, 
           crs="+proj=longlat +datum=WGS84")
```

Reduce grid size

```{r}
this_raster <- rast(ncols=360, nrows=180, crs="+proj=longlat +datum=WGS84",
          xmin = -10, xmax = 10, ymin = 50, ymax = 60)
this_raster[500] <- 1
plot(this_raster)
```



```{r}
this_calculation <- distance(this_raster, this_vector)
```

```{r}
plot(this_calculation)
plot(this_vector,add=T)
```

```{r}
library(terra)
library(ggplot2)
```

```{r}
head(this_calculation)
```

```{r}
this_layers<-as.data.frame(this_calculation, xy = TRUE)
```

```{r}
ggplot(data = this_layers) +
    geom_raster(aes(x = x, y = y, fill = lyr.1)) +
    scale_fill_viridis_c() +
    theme_void() +
    theme(
      legend.position = "bottom"
    )
```

#### export

```{r}
library(here)
this_folder<-paste0(here(),"/_posts/2024-10-23-distancecolony")
this_folder
```


```{r}
writeRaster(this_calculation, filename=file.path(this_folder, "test2.tif"))
```


### adapt 4

```{r}
colony_lat=c(55.25,56.78,56.08,54.15,51.59,53.80,59.54,58.29,60.13,51.73,52.12,54.18,60.71,53.40,53.49,49.70,51.78,62.10,60.14,49.72,48.90,54.67,57.81,59.10,59.08,59.02,57.69,59.29)
colony_long=c(-5.12,-7.64,-2.64,-0.17,-10.27,-10.00,-1.63,-7.59,-2.07,-5.48,-6.62,7.89,-0.88,-6.06,-6.02,-2.24,-10.51,-7.68,-1.02,-2.29,-3.44,-4.70,-8.56,-6.16,-4.41,-4.51,-2.29,-2.98)
```

```{r}
this_colonies<-cbind(colony_long,colony_lat)
```

```{r}
class(this_colonies)
head(this_colonies)
```

```{r}
this_vector <- vect(this_colonies, 
                    crs="+proj=longlat +datum=WGS84")
```

Reduce grid size

```{r}
min(colony_lat)
max(colony_lat)
min(colony_long)
max(colony_long)
```


```{r}
this_raster <- rast(ncols=200, nrows=200, crs="+proj=longlat +datum=WGS84",
          xmin = -15, xmax = 15, ymin = 40, ymax = 70)
this_raster[500] <- 1
plot(this_raster)
```



```{r}
this_calculation <- distance(this_raster, this_vector)
```


```{r}
head(this_calculation)
```

```{r}
this_layers<-as.data.frame(this_calculation, xy = TRUE)
```

```{r}
this_layers$kms<-this_layers$lyr.1/1000
```

```{r}
mean(this_layers$kms)
range(this_layers$kms)
```

```{r}
colonies_sub<-data.frame(
  name=c("Ailsa Craig","Barra Head","Bass Rock","Bempton Cliff","Bull Rock","Clare Island", "Fair Isle", "Flannan Isles","Foula","Grassholm Island","Great Saltee", "Helgoland" , "Hermaness", "Ireland’s Eye", "Lambay", "Les Etac/Alderrney","Little Skellig","Mykinesholmur","Noss" ,"Ortac","Rouzic Island","Scar Rocks","St. Kilda","Sula sgeir","Sule Skerry","Sule Stack","Troup Head","Westray"),
colony_lat=colony_lat,
colony_long=colony_long)
```


```{r}
ggplot(data = this_layers) +
    geom_raster(aes(x = x, y = y, fill = kms)) +
    scale_fill_viridis_c() +
    theme_void() +
    theme(
      legend.position = "bottom"
    )+
  geom_point(data=colonies_sub,aes(x=colony_long,y=colony_lat),color='white')
```

```{r}
Europe<-GermanNorthSea::German_land
Europe<-st_transform(Europe,4326)
```

```{r}
ggplot(data = this_layers) +
  geom_raster(aes(x = x, y = y, fill = kms)) +
  scale_fill_viridis_c() +
  
  geom_sf(data=Europe, colour = 'black', fill = '#2b2d42') +
  geom_point(data=colonies_sub,aes(x=colony_long,y=colony_lat),color='white')+
  
  theme_bw()+
  theme(
  panel.background = element_rect(fill = '#edf2f4'),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),legend.position='none',
  panel.border = element_rect(colour = "black", fill=NA, size=1.5),
  axis.text.x = element_text(size=10,vjust = 10,color='white'),
  axis.text.y = element_text(color='white',size=10,margin = margin(0,-1.00,0,1, unit = 'cm')),
  axis.title = element_blank(),
  axis.ticks.length=unit(-0.20, "cm"),
  )+
  
  coord_sf(xlim = c(-12, 10),ylim = c(48, 63))+
  scale_x_continuous(breaks = c(-10,-5,0,5,10,20,30),labels = function(x) paste0(x, '\u00B0')) +
  scale_y_continuous(breaks = c(45,50,55,60,65,70,75),labels = function(x) paste0(x, '\u00B0'))  +
  
  theme(
      legend.position = "bottom"
    )+

  NULL
```



#### export

```{r}
library(here)
this_folder<-paste0(here(),"/_posts/2024-10-23-distancecolony")
this_folder
```


```{r}
writeRaster(this_calculation, filename=file.path(this_folder, "test3.tif"))
```

```{r}
write_csv(colonies_sub,paste0(this_folder,"/colonies3.txt"))
```

### adapt 5

```{r}
colony_lat=c(55.25,56.78,56.08,54.15,51.59,53.80,59.54,58.29,60.13,51.73,52.12,54.18,60.71,53.40,53.49,49.70,51.78,62.10,60.14,49.72,48.90,54.67,57.81,59.10,59.08,59.02,57.69,59.29)
colony_long=c(-5.12,-7.64,-2.64,-0.17,-10.27,-10.00,-1.63,-7.59,-2.07,-5.48,-6.62,7.89,-0.88,-6.06,-6.02,-2.24,-10.51,-7.68,-1.02,-2.29,-3.44,-4.70,-8.56,-6.16,-4.41,-4.51,-2.29,-2.98)
```

```{r}
this_colonies<-cbind(colony_long,colony_lat)
```

```{r}
class(this_colonies)
head(this_colonies)
```

```{r}
this_vector <- vect(this_colonies, 
                    crs="+proj=longlat +datum=WGS84")
```

Reduce grid size

```{r}
min(colony_lat)
max(colony_lat)
min(colony_long)
max(colony_long)
```


```{r}
this_raster <- rast(ncols=200, nrows=200, crs="+proj=longlat +datum=WGS84",
          xmin = -15, xmax = 15, ymin = 40, ymax = 70)
this_raster[500] <- 1
plot(this_raster)
```



```{r}
this_calculation <- distance(this_raster, this_vector)
```


```{r}
head(this_calculation)
```

```{r}
this_layers<-as.data.frame(this_calculation, xy = TRUE)
```

```{r}
this_layers$kms<-this_layers$lyr.1/1000
```

```{r}
mean(this_layers$kms)
range(this_layers$kms)
```

```{r}
colonies_sub<-data.frame(
  name=c("Ailsa Craig","Barra Head","Bass Rock","Bempton Cliff","Bull Rock","Clare Island", "Fair Isle", "Flannan Isles","Foula","Grassholm Island","Great Saltee", "Helgoland" , "Hermaness", "Ireland’s Eye", "Lambay", "Les Etac/Alderrney","Little Skellig","Mykinesholmur","Noss" ,"Ortac","Rouzic Island","Scar Rocks","St. Kilda","Sula sgeir","Sule Skerry","Sule Stack","Troup Head","Westray"),
colony_lat=colony_lat,
colony_long=colony_long)
```


```{r}
ggplot(data = this_layers) +
    geom_raster(aes(x = x, y = y, fill = kms)) +
    scale_fill_viridis_c() +
    theme_void() +
    theme(
      legend.position = "bottom"
    )+
  geom_point(data=colonies_sub,aes(x=colony_long,y=colony_lat),color='white')
```

```{r}
Europe<-GermanNorthSea::German_land
Europe<-st_transform(Europe,4326)
```

```{r}
ggplot(data = this_layers) +
  geom_raster(aes(x = x, y = y, fill = kms)) +
  scale_fill_viridis_c() +
  
  geom_sf(data=Europe, colour = 'black', fill = '#2b2d42') +
  geom_point(data=colonies_sub,aes(x=colony_long,y=colony_lat),color='white')+
  
  theme_bw()+
  theme(
  panel.background = element_rect(fill = '#edf2f4'),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),legend.position='none',
  panel.border = element_rect(colour = "black", fill=NA, size=1.5),
  axis.text.x = element_text(size=10,vjust = 10,color='white'),
  axis.text.y = element_text(color='white',size=10,margin = margin(0,-1.00,0,1, unit = 'cm')),
  axis.title = element_blank(),
  axis.ticks.length=unit(-0.20, "cm"),
  )+
  
  coord_sf(xlim = c(-12, 10),ylim = c(48, 63))+
  scale_x_continuous(breaks = c(-10,-5,0,5,10,20,30),labels = function(x) paste0(x, '\u00B0')) +
  scale_y_continuous(breaks = c(45,50,55,60,65,70,75),labels = function(x) paste0(x, '\u00B0'))  +
  
  theme(
      legend.position = "bottom"
    )+

  NULL
```



#### export

```{r}
library(here)
this_folder<-paste0(here(),"/_posts/2024-10-23-distancecolony")
this_folder
```


```{r}
writeRaster(this_calculation, filename=file.path(this_folder, "test3.tif"))
```

```{r}
write_csv(colonies_sub,paste0(this_folder,"/colonies3.txt"))
```

# Further reading

This could be use also with distance to the nearest boat, for gulls for example.





# End of document