---
title: "Arrows"
output: html_document
date: "2023-11-16"
---

# Functions

# S5


### identify events


### rescale_event

```{r}
rescale_events<-function(my_data=my_data,each_num=each_num){
  
  events_list<-split(my_data,my_data$event_number)
  
  new_events_list<-list()
  
  for( i in seq_along(events_list)){
    
    events_df<-events_list[[i]]
    
    rep_secuence<-rep(1:100, each=each_num)
    replicate_numbers<-rep_secuence[1:nrow(events_df)]
    
    events_df$rep_number<-replicate_numbers
    
    events_df$event_number2<-paste0(events_df$event_number,'-',events_df$rep_number)
    
    new_events_list[[i]]<-events_df
  }

new_events_df<- do.call("rbind",new_events_list)

return(new_events_df)
  
}
```

# 1. Load data

```{r}
library(sula)
```

```{r}
GPS_edited
```

# 2. Format data

### rename

```{r}
my_data<- GPS_edited %>%
  filter(IDs=='GPS01',trip_number=='trip_1') %>%
  rename(LAT=Latitude,
         LON=Longitude,
         DATE=tStamp)
```

### add sequence

```{r}
my_data2<-my_data %>%
  arrange(DATE)%>%
  mutate(trip_seq=1:nrow(my_data))
```

```{r}
ggplot()+
  geom_point(data=my_data2,
          aes(x = LON,
              y= LAT,
          color=trip_seq))
```

### start and end

```{r}
my_start<-first(my_data2)
my_end<-last(my_data2)
```

```{r}
ggplot()+
  geom_point(data=my_data2,
          aes(x=LON, y= LAT,
          color=trip_seq))+
  geom_point(data=my_start,
          aes(x = LON, y= LAT
              ), 
          color='red', size=2)+
  geom_point(data=my_end,
          aes(x = LON, y= LAT
              ), color='yellow', size=2)
```

### calculate gaps

```{r}
my_data2$dt <- as.POSIXct(strptime(my_data2$DATE, "%Y-%m-%d %H:%M:%S"))
```

```{r}
calculate_gaps<-function(my_data=my_data){
  Time1<-my_data$dt
  Time2<-lag(Time1)
  Time_dif<-as.numeric(difftime(Time1,Time2, units="mins"))
  my_data$time_dif<-as.numeric(Time_dif)
  return(my_data)
}
```

```{r}
my_data3<-calculate_gaps(my_data2)
```

```{r}
unique(my_data3$time_dif,na.rm=TRUE)
```

```{r}
my_data4 <- my_data3 %>%
  mutate(gap_event = case_when(is.na(time_dif) ~ 'N',
                                time_dif >= 4 ~ 'Y',
                                TRUE ~ 'N'))
```

### identify events

```{r}
identify_events<-function(my_data=my_data){
  
  num_seq<-nrow(my_data)
  num_seq<-as.numeric(num_seq)
  my_data$num_seq<-paste(seq(1:num_seq))
  
  #subset only trips
  subset_data<-subset(my_data,my_data$gap_event != "Y")
  
  subset_data$num_seq<-as.integer(subset_data$num_seq)
  
  #subset only trips
  subset_data$event_number<-(cumsum(c(1L, diff(subset_data$num_seq)) != 1L))
  subset_data$event_number<-subset_data$event_number+1
  subset_data$event_number<-stringr::str_pad(subset_data$event_number, 3, pad = "0")
  subset_data$event_number<-paste0("event_",subset_data$event_number)

return(subset_data)
}
```

```{r}
my_data5<-identify_events(my_data=my_data4)
```

```{r}
unique(my_data5$event_number)
```

```{r}
ggplot()+
  geom_point(data=my_data5,
          aes(x = LON,
              y= LAT,
          color=event_number))
```
### arrow

```{r}
S5_Obs6_arrow<-S5_Obs5_events %>%
  group_by(event_number)%>%
  summarise(first_lat=first(LAT),
            last_lat=last(LAT),
            first_lon=first(LON),
            last_lon=last(LON))
```

```{r}
ggplot(S5_Obs6_arrow,
       aes(x = first_lon, y = first_lat)) +
  geom_segment(aes(xend = last_lon, yend = last_lat), arrow = arrow())
```

### rescale 

```{r}
S5_Obs6_rescale<-rescale_events(my_data=S5_Obs5_events,each_num=700)
```


### group by event

```{r}
S5_Obs6_arrow2<-S5_Obs6_rescale %>%
  group_by(event_number2)%>%
  summarise(first_lat=first(LAT),
            last_lat=last(LAT),
            first_lon=first(LON),
            last_lon=last(LON))
```

### plot 

```{r}
ggplot(S5_Obs6_arrow2,
       aes(x = first_lon, y = first_lat)) +
  geom_segment(aes(xend = last_lon, yend = last_lat), 
               arrow = arrow())
```

```{r}
Germany_plot+  
  geom_segment(data=S5_Obs6_arrow2,aes(x = first_lon, y = first_lat,xend = last_lon, yend = last_lat), 
               arrow = arrow(length=unit(0.19,"cm"), type = "closed"),color='#c1121f')+
    geom_point(data=S5_Obs_start,
          aes(x = LON,
              y= LAT
              ), 
            fill='black', size=2, shape=21)+
  geom_point(data=S5_Obs_end,
          aes(x = LON,
              y= LAT
              ), fill='black', size=2,shape=23)
```
